### ISSUE TITLE
No class found Exception setting up DataConnector in attributes-resolver.xml

### ISSUE THREAD

**Issue by tsschmidt** [apereo/cas#2157]
Working with 5.1.0-SNAPSHOT and trying to setup Shibboleth attributes-resolver.xml.  We need to use a different ldap connection than what we use to authenticate for attribute resolution.  Getting the following error when deploying with an attributes-resolver.xml that has a DataConnector defined.

```
Caused by: java.lang.NoClassDefFoundError: org/ldaptive/provider/ConnectionStrategy
	at net.shibboleth.idp.attribute.resolver.spring.dc.ldap.impl.LDAPDataConnectorParser.doV2Parse(LDAPDataConnectorParser.java:134) ~[idp-attribute-resolver-spring-3.2.1.jar:?]
	at net.shibboleth.idp.attribute.resolver.spring.dc.impl.AbstractDataConnectorParser.doParse(AbstractDataConnectorParser.java:157) ~[idp-attribute-resolver-spring-3.2.1.jar:?]
	at org.springframework.beans.factory.xml.AbstractSingleBeanDefinitionParser.parseInternal(AbstractSingleBeanDefinitionParser.java:85) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.xml.AbstractBeanDefinitionParser.parse(AbstractBeanDefinitionParser.java:61) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at net.shibboleth.ext.spring.util.BaseSpringNamespaceHandler.parse(BaseSpringNamespaceHandler.java:96) ~[spring-extensions-5.2.0.jar:?]
	at net.shibboleth.ext.spring.util.SchemaTypeAwareBeanDefinitionParserDelegate.parseCustomElement(SchemaTypeAwareBeanDefinitionParserDelegate.java:66) ~[spring-extensions-5.2.0.jar:?]
	at net.shibboleth.ext.spring.util.SchemaTypeAwareBeanDefinitionParserDelegate.parseCustomElement(SchemaTypeAwareBeanDefinitionParserDelegate.java:49) ~[spring-extensions-5.2.0.jar:?]
	at net.shibboleth.ext.spring.util.SpringSupport.parseCustomElement(SpringSupport.java:178) ~[spring-extensions-5.2.0.jar:?]
	at net.shibboleth.ext.spring.util.SpringSupport.parseCustomElements(SpringSupport.java:157) ~[spring-extensions-5.2.0.jar:?]
	at net.shibboleth.idp.attribute.resolver.spring.impl.AttributeResolverParser.parse(AttributeResolverParser.java:68) ~[idp-attribute-resolver-spring-3.2.1.jar:?]
	at net.shibboleth.ext.spring.util.BaseSpringNamespaceHandler.parse(BaseSpringNamespaceHandler.java:96) ~[spring-extensions-5.2.0.jar:?]
	at net.shibboleth.ext.spring.util.SchemaTypeAwareBeanDefinitionParserDelegate.parseCustomElement(SchemaTypeAwareBeanDefinitionParserDelegate.java:66) ~[spring-extensions-5.2.0.jar:?]
	at net.shibboleth.ext.spring.util.SchemaTypeAwareBeanDefinitionParserDelegate.parseCustomElement(SchemaTypeAwareBeanDefinitionParserDelegate.java:49) ~[spring-extensions-5.2.0.jar:?]
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:178) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:142) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:94) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:508) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:392) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:181) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at net.shibboleth.ext.spring.util.SpringSupport.newContext(SpringSupport.java:125) ~[spring-extensions-5.2.0.jar:?]
```

**Comment by mmoayyed** [comment]
Is ldaptive anywhere on the classpath?

**Comment by tsschmidt** [comment]
yes, in cas-server-support-ldap

**Comment by mmoayyed** [comment]
Share your resolver xml please.

**Comment by tsschmi** [comment]
<resolver:DataConnector id="ucdLDAP" xsi:type="dc:LDAPDirectory"
        ldapURL="LDAP_URL"
        baseDN="BASE_DN"
        principal="PRINCIPAL"
        principalCredential="CREDENTIAL"
        useStartTLS="true">
        <dc:FilterTemplate>
            <![CDATA[
                (uid=$requestContext.principalName)
            ]]>
        </dc:FilterTemplate>
    </resolver:DataConnector>

**Comment by tsschmidt** [comment]
Looks like I found the issue.  The shibbleth IdP jars appear to be compiled against Ldaptive 1.1.1 and the 5.1.0-SNAPSHOT was updated to 1.2.1

**Comment by mmoayyed** [comment]
Possibly, but I do see the same missing class in 1.2.1 as well. My guess is that when the IdP context is created to resolve attributes, it's not loading the ldaptive jar at all.

**Comment by tsschmidt** [comment]
ConnectionStrategy was removed from Ldaptive 1.2.1.  If you look at
LDAPDataConnectorParser from the shib-idp-3.2.1.jar, it is trying to use
ConnectionStrategy which only exists in versions of Ldaptive < 1.2.0

**Comment by mmoayyed** [comment]
OK we did a little checking. If you review ldaptive tags on github you'll find the `ConnectionStrategy` available for both 1.2.1 and 1.2.0. However, it seems like it's not quite available for 1.1 and below which makes sense since the IdP uses an older version of it.

Have you tried forcing 1.0.x for ldaptive and see if that makes a difference? What's your use case?

**Comment by tsschmidt** [comment]
It looks like it has been refactored to reside a package higher. The idp 
jar is looking for it under org.ldaptive.provider.   I tried to 
downgrade to 1.1.1, but then Beans.java and other ldap config classes 
complained.

**Comment by tsschmidt** [comment]
I tried upgrading to shib idp 3.3.0 library jar, but I get the same 
error.  It looks to me like it might be built with version 1.0.9

https://build.shibboleth.net/nexus/content/repositories/thirdparty/org/ldaptive/ldaptive/

For CAS to be compatible it would need to be downgraded.

**Comment by mmoayyed** [comment]
Gotcha. We are not going to downgrade; you could potentially open a JIRA with Shibboleth and ask them to upgrade to latest ldaptive? That may already be on the roadmap in fact.

**Comment by mmoayyed** [comment]
Actually we might be able to circumvent this somehow; I think rather than having you use an attribute-resolver.xml file we might be able to adopt the same strategy we have with person directory and just manually autowire everything based on cas properties. So we'd just be using data connectors as a framework underneath and we could expose properties for ldap and rdbms data connectors easily. I think this strategy will basically have you declare attribute definitions in an xml file (and that we might also be able to do away with, specially if we let each resolver control its own attributes as is described in #2083 )

**Comment by tsschmi** [comment]
I started down that path Friday afternoon then I found
cas.ldap.attributesRepository which should do exactly what I am looking
for.  I will verify it first thing in the morning that it works.  Maybe
just need to note that DataConnectors of type LDAPDirectory will not be
supported in Shibboleth attribute-resolver.xml.

**Comment by mmoayyed** [comment]
Yup. We very well could advertise; I am however moving more and more towards removing the ability to support the xml file. At the time when we supported this behavior, configuring person-directory was just too difficult, but now that it's all props-based I wonder if we could just automate it all. What do you think?

**Comment by mmoayyed** [comment]
I have made sure the crash is accounted for and caught with a warning message. I will also update the docs for the time being to make the ldap incompatibilities known. Thanks very much for the report. LMK if you find anything buggy on the attributes side.

**Comment by mmoayyed** [comment]
FYI https://issues.shibboleth.net/jira/browse/IDP-1095
