### PR TITLE
Support for European e-identification

### PR DESCRIPTION
**Pull request by luis100**
Integration with the [European eId](https://ec.europa.eu/digital-single-market/en/e-identification), specifically with [Portuguese implementation](https://www.autenticacao.gov.pt/) that use the  SAML2 protocol via pac4j.

Allowing to define pac4j saml new configurations:
 - signature signing algorithms
 - provider name
 - authn request extensions
 - using attribute as the principal Id

This pull request depends on the pac4j update after merging with https://github.com/pac4j/pac4j/pull/1128, hopefully on pac4j version 3.0.0-RC3.

### CODE REVIEW

**Comment by luis100** [comment]
Besides being blocked by a pac4j pull request, this code currently fails due to the following error:
```
2018-04-12 11:36:31,454 WARN [org.apereo.cas.web.flow.resolver.impl.InitialAuthenticationAttemptWebflowEventResolver] - <No authentication result builder can be located in the context>
java.lang.IllegalArgumentException: No authentication result builder can be located in the context
```

The code works on CAS version 5.2.3, integration code available at branch https://github.com/luis100/cas/tree/keeps_supportEuropeanEID_5.2.3

**Comment by leleuj** [comment]
@luis100 I just merged your pac4j changes...

**Comment by mmoayyed** [comment]
These seem related to your changes:

```
:support:cas-server-support-openid:compileTestJava/home/travis/build/apereo/cas/support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/authentication/DelegatedClientFactory.java:382: error: cannot find symbol
                    cfg.setProviderName(saml.getProviderName());
                       ^
  symbol:   method setProviderName(String)
  location: variable cfg of type SAML2ClientConfiguration
/home/travis/build/apereo/cas/support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/authentication/DelegatedClientFactory.java:385: error: cannot find symbol
                    cfg.setAuthnRequestExtensions(() -> parseExtensions(saml.getAuthnRequestExtensions()));
                       ^
  symbol:   method setAuthnRequestExtensions(()->parseE[...]ns()))
  location: variable cfg of type SAML2ClientConfiguration
/home/travis/build/apereo/cas/support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/authentication/DelegatedClientFactory.java:388: error: cannot find symbol
                    cfg.setAttributeAsId(saml.getAttributeAsId());
                       ^
  symbol:   method setAttributeAsId(String)
  location: variable cfg of type SAML2ClientConfiguration
Note: /home/travis/build/apereo/cas/support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/authentication/DelegatedClientFactory.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
```

**Comment by luis100** [comment]
Those are because my changes on the pac4j Library, which were already merged in pac4j's master and 2.2.x branches, are not yet integrated here. Guess we'll have to wait for them to be release on the 3.0.0-RC3 release.

**Comment by luis100** [comment]
@mmoayyed the pac4j RC2 was release with my changes, so we can resume work. Could you re-open this pull request so I don't miss the review story?
